apiVersion: v1
kind: Service
metadata:
  name: partner-api
  namespace: pre-production
  labels:
    cis.f5.com/as3-tenant: QA
    cis.f5.com/as3-app: MyAPIs
    cis.f5.com/as3-pool: api_pool
spec:
  selector:
    app: partner-api
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP